### ISSUE TITLE
Student homework?

### ISSUE THREAD

**Issue by XuTpuK** [nin-jin/tree.d#1]
This format is not a character better than JSON, but having even more limits: what is that sh!t "value cannot contain newline"?? Value CAN and WILL contain newline! So if your format doesn't support newlines, dude, just relax and don't fart the air with your so called "format"!

**Comment by nin-jin** [comment]
value-nodes (aka data-nodes) can not contain new lines, because that uses as data-node terminal. Multiline text must be represented as list of data-nodes. This allows you to safe store binary data and easy to read text data.

**Comment by nin-jin** [comment]
You can read more in this article: http://habrahabr.ru/post/248147/

**Comment by demonkoryu** [comment]
Although I find Xutpuks behaviour deplorable, it would be great if you could translate that article to english and include it as part of the documentation in your repo.
I've made a request for that: #2

Thanks.

**Comment by RichardFevrier** [comment]
[https://hackernoon.com/tree-ast-which-crushes-json-xml-yaml-toml-etc](https://hackernoon.com/tree-ast-which-crushes-json-xml-yaml-toml-etc)
